/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author duchi
 */
public class ListOfUsers extends javax.swing.JFrame {

    /**
     * Creates new form ListOfUsers
     */
    public ListOfUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRegisteredUser = new javax.swing.JList<>();
        jBtnChat = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jBtn_OfflineMessages = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("List of users");

        jLabelUserName.setText("Login as:");

        jLabel1.setText("Registered users:");

        jListRegisteredUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListRegisteredUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListRegisteredUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListRegisteredUser);

        jBtnChat.setText("Chat");
        jBtnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChatActionPerformed(evt);
            }
        });

        jBtnClose.setText("Close");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jBtn_OfflineMessages.setText("Offline messages");
        jBtn_OfflineMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_OfflineMessagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnChat, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_OfflineMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserName)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnChat)
                    .addComponent(jBtnClose)
                    .addComponent(jBtn_OfflineMessages))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListRegisteredUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListRegisteredUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListRegisteredUserMouseClicked

    private void jBtn_OfflineMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_OfflineMessagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_OfflineMessagesActionPerformed

    private void jBtnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnChatActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    public JButton getjBtnChat() {
        return jBtnChat;
    }

    public void setjBtnChat(JButton jBtnChat) {
        this.jBtnChat = jBtnChat;
    }

    public JButton getjBtnClose() {
        return jBtnClose;
    }

    public void setjBtnClose(JButton jBtnClose) {
        this.jBtnClose = jBtnClose;
    }

    public JButton getjBtn_OfflineMessages() {
        return jBtn_OfflineMessages;
    }

    public void setjBtn_OfflineMessages(JButton jBtn_OfflineMessages) {
        this.jBtn_OfflineMessages = jBtn_OfflineMessages;
    }

    public JLabel getjLabelUserName() {
        return jLabelUserName;
    }

    public void setjLabelUserName(JLabel jLabelUserName) {
        this.jLabelUserName = jLabelUserName;
    }

    public JList<String> getjListRegisteredUser() {
        return jListRegisteredUser;
    }

    public void setjListRegisteredUser(JList<String> jListRegisteredUser) {
        this.jListRegisteredUser = jListRegisteredUser;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChat;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtn_OfflineMessages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JList<String> jListRegisteredUser;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
